debs: Fixup linux to 6.12.27-1~bpo12+1.debian update
There was new issue not seen as a merge conflict:

drivers/platform/x86/intel/int3472/discrete.c: In function ‘skl_int3472_map_gpio_to_sensor’:
drivers/platform/x86/intel/int3472/discrete.c:102:17: error: ‘polarity’ undeclared (first use in this function)
  102 |                 polarity ^= GPIO_ACTIVE_LOW;
      |                 ^~~~~~~~
drivers/platform/x86/intel/int3472/discrete.c:102:17: note: each undeclared identifier is reported only once for each function it appears in

Rename the parameter as `polarity` (and remember to check this out also
in future kernel updates).

Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@opinsys.com>